# --- Dr.ReinforceR specific parameters ---

action_selector: "multinomial"
epsilon_start: .5
epsilon_finish: .01
epsilon_anneal_time: 100000
mask_before_softmax: False

runner: "parallel"

buffer_size: 8
batch_size_run: 8
batch_size: 8

env_args:
  state_last_action: False # critic adds last action internally

lr: 0.0025
reward_lr: 0.0025

# use Dr.ReinforceR
agent_output_type: "pi_logits"
learner: "drreinforcer_learner"
reward_fn: "centralized_r"
reward_baseline_fn: "au"
reward_train_mode: "seq"
reward_train_reps: 1

name: "drreinforcer"
